myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .views import recipe_detail

urlpatterns = [
    path('', views.index, name='index'),
    path('create_category/', views.create_category, name='create_category'),
    path('create_user/', views.create_user_profile, name='create_user'),
    path('create_recipe/', views.create_recipe, name='create_recipe'),
    path('add_ingredient/', views.add_ingredient, name='add_ingredient'),
    path('recipe_detail/<int:recipe_id>/', recipe_detail, name='recipe_detail'),
    path('delete_recipe/<int:recipe_id>/', views.delete_recipe, name='delete_recipe'),
    path('edit_recipe/<int:recipe_id>/', views.edit_recipe, name='edit_recipe'),
    path('author_detail/<int:author_id>/', views.author_detail, name='author_detail'),
    path('edit_user/<int:author_id>/', views.edit_user, name='edit_user'),
    path('delete_user/<int:author_id>/', views.delete_user, name='delete_user'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=50)
    bio = models.TextField(blank=True, null=True)
    photo = models.ImageField(upload_to='author_photos/', blank=True, null=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    ingredients = models.ManyToManyField(Ingredient)
    directions = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

recipe/forms/add_ingridient.py
from django import forms
from ..models import Ingredient


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name']

recipe/forms/category_add_form.py
from django import forms
from ..models import Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']

recipe/forms/new_recipe_form.py
# forms.py
from django import forms
from ..models import Recipe, Ingredient


class RecipeForm(forms.ModelForm):
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Recipe
        fields = ['title', 'description', 'ingredients', 'directions', 'image', 'author', 'category']

    directions = forms.CharField(
        label="Ход приготовления",
        widget=forms.Textarea(attrs={'cols': 80, 'rows': 20})
    )

recipe/forms/new_user_profile_form.py
from django import forms
from ..models import Author


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'photo', 'bio']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter author name', 'maxlength': '200'}),
        }
        labels = {
            'name': 'Author name',
            'photo': 'Author photo',
            'bio': 'Author bio',
        }
        help_texts = {
            'name': 'Введите имя пользователя',
            'photo': 'Загрузите фотографию пользователя',
            'bio': 'Личная информация о пользователе',
        }

    def clean_name(self):
        data = self.cleaned_data['name']
        if len(data) < 3:
            raise forms.ValidationError('Имя пользователя должно быть больше 3 символов')
        return data

    def clean_photo(self):
        data = self.cleaned_data['photo']
        if data:
            if len(data.name) > 100:
                raise forms.ValidationError('Имя файла фотографии не должно превышать 100 символов')
        return data

recipe/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseBadRequest
from .forms.category_add_form import CategoryForm
from .forms.new_user_profile_form import AuthorForm
from .forms.new_recipe_form import RecipeForm
from .forms.add_ingridient import IngredientForm
from .models import Recipe, Author


def generate_links():
    return [
        {'url': reverse('index'), 'text': 'Главная'},
        {'url': reverse('create_recipe'), 'text': 'Создать рецепт'},
        {'url': reverse('create_category'), 'text': 'Создать категорию'},
        {'url': reverse('create_user'), 'text': 'Создать пользователя'},
        {'url': reverse('add_ingredient'), 'text': 'Добавить ингредиент'},
    ]


def index(request):
    links = generate_links()
    recipes = Recipe.objects.all()
    chefs = Author.objects.all()

    return render(request, 'recipe/index.html', {'links': links, 'chefs': chefs, 'recipes': recipes})


def recipe_detail(request, recipe_id):
    links = generate_links()
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    ingredients_list = recipe.ingredients.all()
    return render(request, 'recipe/recipe.html', {'links': links, 'recipe': recipe, 'ingredients_list': ingredients_list})


def create_category(request):
    links = generate_links()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = CategoryForm()

    return render(request, 'recipe/create_category.html', {'links': links, 'form': form})


def create_user_profile(request):
    links = generate_links()
    if request.method == 'POST':
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = AuthorForm()

    return render(request, 'recipe/create_user.html', {'links': links, 'form': form})


def create_recipe(request):
    links = generate_links()
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = RecipeForm()

    return render(request, 'recipe/create_recipe.html', {'links': links, 'form': form})


def add_ingredient(request):
    links = generate_links()
    if request.method == 'POST':
        form = IngredientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = IngredientForm()

    return render(request, 'recipe/add_ingredient.html', {'links': links, 'form': form})


def delete_recipe(request, recipe_id):
    if request.method == 'POST':
        recipe = get_object_or_404(Recipe, id=recipe_id)
        recipe.delete()
        return redirect('index')
    else:
        return HttpResponseBadRequest("Invalid request method.")


def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('recipe_detail', recipe_id=recipe.id)
    else:
        form = RecipeForm(instance=recipe)

    context = {'links': links, 'form': form, 'recipe': recipe}
    return render(request, 'recipe/edit_recipe.html', context)


def author_detail(request, author_id):
    links = generate_links()
    author = get_object_or_404(Author, id=author_id)
    return render(request, 'recipe/author_detail.html', {'links': links, 'author': author})


def edit_user(request, author_id):
    author = get_object_or_404(Author, id=author_id)

    if request.method == 'POST':
        form = AuthorForm(request.POST, request.FILES, instance=author)
        if form.is_valid():
            form.save()
            return redirect('author_detail', author_id=author.id)
    else:
        form = AuthorForm(instance=author)

    context = {'links': generate_links(), 'form': form, 'author': author}
    return render(request, 'recipe/edit_user.html', context)


def delete_user(request, author_id):
    author = get_object_or_404(Author, id=author_id)

    if request.method == 'POST':
        author.delete()
        return redirect('index')
    else:
        context = {'links': generate_links(), 'author': author}
        return render(request, 'recipe/delete_user.html', context)

recipe/templates/recipe/add_ingredient.html
{% extends 'base.html' %}

{% block title %}
  Добавить ингредиент
{% endblock %}

{% block content %}
    <h2>Добавить ингридиет</h2>
    <form method="post" action="{% url 'add_ingredient' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>

{% endblock %}

recipe/templates/recipe/author_detail.html
{% extends 'base.html' %}

{% block title %}
  Детали автора: {{ author.name }}
{% endblock %}

{% block content %}
  <h2>{{ author.name }}</h2>
  <p>Биография: {{ author.bio }}</p>

  {% if author.photo %}
    <img src="{{ author.photo.url }}" alt="{{ author.name }}">
  {% endif %}

  <h3>Рецепты автора:</h3>
  <ul>
    {% for recipe in author.recipe_set.all %}
      <li><a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.title }}</a></li>
    {% endfor %}
  </ul>

  <a href="{% url 'edit_user' author_id=author.id %}">Изменить пользователя</a>
{% endblock %}

recipe/templates/recipe/create_category.html
{% extends 'base.html' %}

{% block title %}
  Создать новую категорию
{% endblock %}

{% block content %}
    <h2>Создать категорию</h2>
    <form method="post" action="{% url 'create_category' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>

{% endblock %}

recipe/templates/recipe/create_recipe.html
{% extends 'base.html' %}

{% block title %}
  Создать рецепт
{% endblock %}

{% block content %}
    <h2>Создать рецепт</h2>
    <form method="post" action="{% url 'create_recipe' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>
{% endblock %}

recipe/templates/recipe/create_user.html
{% extends 'base.html' %}

{% block title %}
  Создать пользователя
{% endblock %}

{% block content %}
    <h2>Создать пользователя</h2>
    <form method="post" action="{% url 'create_user' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>
{% endblock %}

recipe/templates/recipe/edit_recipe.html
{% extends 'base.html' %}

{% block title %}
  Редактировать рецепт {{ recipe.title }}
{% endblock %}

{% block content %}
   <h2>Редактировать рецепт</h2>
   <form method="post" action="{% url 'edit_recipe' recipe.id %}" enctype="multipart/form-data">
       {% csrf_token %}
       {{ form.as_p }}
       <button type="submit">Сохранить изменения</button>
   </form>
{% endblock %}

recipe/templates/recipe/edit_user.html
{% extends 'base.html' %}

{% block content %}
  <h1>Изменить пользователя</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button>
  </form>

  <form method="post" action="{% url 'delete_user' author.id %}">
    {% csrf_token %}
    <button type="submit" onclick="return confirm('Вы уверены?')">Удалить пользователя</button>
  </form>
{% endblock %}

recipe/templates/recipe/index.html
{% extends 'base.html' %}

{% block title %}
  Главная страница
{% endblock %}

{% block content %}

    <section class="container text-center">
        <h3>Повара:</h3><br>
        <div class="row justify-content-center">
            {% if chefs %}
                {% for author in chefs %}
                    <div class="col-md-4 mb-3 chef-item">
                        <article class="author">
                            <div class="card" style="width: 18rem;">
                                {% if author.photo %}
                                    <img src="{{ author.photo.url }}" alt="{{ author.name }}">
                                {% else %}
                                    <img src="..." class="card-img-top" alt="...">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title">{{ author.name }}</h5>
                                    <p class="card-text">{{ author.bio }}</p>
                                    <a href="{% url 'author_detail' author.id %}" class="btn btn-primary">Подробнее об авторе</a>
                                </div>
                            </div>
                        </article>
                    </div>
                    {% if forloop.counter|divisibleby:3 %}<div class="w-100"></div>{% endif %}
                {% endfor %}
            {% else %}
                <p>Нет доступных поворов.</p>
            {% endif %}
        </div>
    </section>

    <div class="container d-flex justify-content-center my-3">
        <h2>Самые популярные рецепты</h2>
    </div>

    <section>

        {% if recipes %}
            {% for recipe in recipes %}
                <div class="card mx-3">
                    <h5 class="card-header">{{ recipe.title }}</h5>
                    <div class="card-body">
                        <h5 class="card-title">Автор: <a href="{% url 'author_detail' recipe.author.id %}">{{ recipe.author.name }}</a></h5>
                        <p class="card-text">{{ recipe.description }}</p>
                        <a href="{% url 'recipe_detail' recipe.id %}" class="btn btn-primary">Ссылка на рецепт</a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>Нет доступных рецептов.</p>
        {% endif %}

    </section>

{% endblock %}

recipe/templates/recipe/recipe.html
{% extends 'base.html' %}

{% block title %}
  Подробности о рецепте {{ recipe.title }}
{% endblock %}

{% block content %}
    <h1>{{ recipe.title }}</h1>

    {% if recipe.image %}
        <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}">
    {% endif %}

    <div>
        <p>{{ recipe.description }}</p>
        <p>Ингредиенты: </p>

        <ul>
            {% for ingredient in ingredients_list %}
                <li>{{ ingredient.name }}</li>
            {% endfor %}
        </ul>

        <p>Инструкции: {{ recipe.directions }}</p>
        <p>Автор: {{ recipe.author.name }}</p>
        <p>Категория: {{ recipe.category.name }}</p>
        <a href="{% url 'index' %}">Назад к списку рецептов</a>

        <form method="post" action="{% url 'delete_recipe' recipe.id %}">
            {% csrf_token %}
            <button type="submit" onclick="return confirm('Вы уверены?')">Удалить рецепт</button>
        </form>
        <br>

        <a href="{% url 'edit_recipe' recipe.id %}">Редактировать рецепт</a>

    </div>

{% endblock %}